add USE_USERNAME config
AzMoo/django-okta-auth pull request #9
Opened 2021-03-01 18:42 UTC by samkuehn

I have an exiting user database that stores username as just username (not email address).  This added a  USE_USERNAME option to the config to allow for this.

2021-03-02 11:11 UTC, AzMoo commented
Hey thanks so much for your contribution, but I can't accept a change like this without tests or docs.

2021-03-02 16:54 UTC, samkuehn commented
Sorry for not adding tests or docs.  I had not used poetry before and was being lazy.  Test and docs have been added

2021-03-05 05:05 UTC, AzMoo requested changes
Please don't commit a `poetry.lock`, we don't need it for a library.

2021-03-06 00:14 UTC, samkuehn commented on okta_oauth2/tokens.py
> +                username = claims["email"].split("@")[0]
Interesting.  Never seen an email with two @'s in it.  Do you thing we need to account for this?

2021-03-08 23:48 UTC, AzMoo approved these changes

2021-03-08 23:48 UTC, merged

2021-03-26 15:39 UTC, samkuehn commented
Any chance we could get this change in released to pypi?

2021-03-26 20:58 UTC, AzMoo commented
Yep, sorry for the delay. I didn't realise the CI had a problem with the code style.